### ISSUE TITLE
Memory error when building Automated Feature Engineering

### ISSUE THREAD

**Issue by BoonHuiYap** [abhishekdbihani/Home-Credit-Default-Risk-Recognition#3]
numpy.core._exceptions.Array MemoryError: Unable to allocate 189. MiB for an array with shape (3, 8251754) and data type object

**Comment by BoonHuiYap** [comment]
Hi. May I know what is reason causing the error message pop out when I tried to run this line of code

"es = es.entity_from_dataframe(entity_id = 'previous', dataframe = previous_application_new, index = 'SK_ID_PREV')"

**Comment by abhishekdbihani** [comment]
Hi, I think this is an issue with your available RAM/memory capacity. I would suggest trying again after closing other applications or using another computer with higher RAM if needed.
